# 15

In [128]:
import pandas as pd

In [129]:
df = pd.read_csv('project/data/nyc_taxi_2019-01.csv', usecols=['passenger_count', 'trip_distance', 'total_amount', 'payment_type'])

In [130]:
df.head()

   passenger_count  trip_distance  payment_type  total_amount
0                1            1.5             1          9.95
1                1            2.6             1         16.30
2                3            0.0             1          5.80
3                5            0.0             2          7.55
4                5            0.0             2         55.55

In [131]:
df.describe()

       passenger_count  trip_distance  payment_type  total_amount
count     7.667792e+06   7.667792e+06  7.667792e+06  7.667792e+06
mean      1.567078e+00   2.801084e+00  1.291776e+00  1.568222e+01
std       1.224431e+00   3.737529e+00  4.733229e-01  2.622932e+02
min       0.000000e+00   0.000000e+00  1.000000e+00 -3.628000e+02
25%       1.000000e+00   9.000000e-01  1.000000e+00  8.190000e+00
50%       1.000000e+00   1.530000e+00  1.000000e+00  1.127000e+01
75%       2.000000e+00   2.800000e+00  2.000000e+00  1.656000e+01
max       9.000000e+00   8.318000e+02  4.000000e+00  6.232617e+05

In [132]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7667792 entries, 0 to 7667791
Data columns (total 4 columns):
 #   Column           Dtype
---  ------           -----
 0   passenger_count  int64
 1   trip_distance    float64
 2   payment_type     int64
 3   total_amount     float64
dtypes: float64(2), int64(2)
memory usage: 234.0 MB

How many taxi rides had more than eight passengers?

In [133]:
df.loc[df['passenger_count'] > 8, 'passenger_count'].count()

np.int64(9)

How many taxi rides had zero passengers?

In [134]:
df.loc[df['passenger_count'] == 0, 'passenger_count'].count()

np.int64(117381)

How many taxi rides were paid for in cash and cost over $1,000?

In [135]:
df.loc[(df['payment_type'] == 2) & (df['total_amount'] > 1000), 'passenger_count'].count()

np.int64(5)

How many rides cost less than $0?

In [136]:
df.loc[df['total_amount'] < 0].shape[0]

7131

How many rides traveled a below-average distance and cost an above-average amount?

In [137]:
df.loc[(df['trip_distance'] < df['trip_distance'].mean()) & (df['total_amount'] > df['total_amount'].mean()), 'trip_distance'].count()

np.int64(411255)

Repeat this exercise using the query method rather than a boolean index and loc.

In [138]:
df.query('passenger_count > 8').shape[0]

9

In [139]:
df.query('passenger_count == 0').shape[0]

117381

In [140]:
df.query('payment_type == 2 and total_amount > 1000').shape[0]

5

In [141]:
df.query('total_amount < 0').shape[0]

7131

In [142]:
df.query('trip_distance < @df["trip_distance"].mean() and total_amount > @df["total_amount"].mean()').shape[0]

411255

How many rides that cost less than $0 involved either a dispute (`payment_type` of 4) or a voided trip (`payment_type` of 6)?

In [143]:
df.loc[(df['total_amount'] < 0) & (df['payment_type'].isin([4, 6]))].shape[0]

2666

In [144]:
df.query('total_amount < 0 and payment_type in [4, 6]').shape[0]

2666

Find what percentage normally pays in cash versus a credit card.

In [145]:
df['payment_type'].value_counts(normalize=True) * 100

payment_type
1    71.546372
2    27.875234
3     0.432797
4     0.145596
Name: proportion, dtype: float64