# 21

In [7]:
import pandas as pd

1 Create a data frame from the file nyc-parking-violations-2020.csv. We are only interested in a handful of the columns:
- Date First Observed
- Plate ID
- Registration State
- Issue Date (a string in MM/DD/YYYY format, always followed by 12:00:00
- Vehicle Make
- Street Name
- Vehicle Color

In [8]:
nyc_pv = pd.read_csv('./data/nyc-parking-violations-2020.csv',
                    usecols=['Date First Observed','Plate ID', 'Registration State', 'Issue Date', 'Vehicle Make', 'Street Name', 'Vehicle Color'])

Set the data frame’s index to the Issue Date column.

In [9]:
df = nyc_pv.set_index('Issue Date')

Determine what three makes were most frequently ticketed on January 2, 2020

In [12]:
df.loc['01/02/2020 12:00:00 AM', 'Vehicle Make'].value_counts().head(3)

Vehicle Make
TOYOT    3829
HONDA    3593
FORD     3164
Name: count, dtype: int64

Determine the five streets on which cars got the most tickets on June 1, 2020.

In [13]:
df.loc['06/01/2020 12:00:00 AM', 'Street Name'].value_counts().head(5)

Street Name
WB CONDUIT BLVD @ LI    1068
SB WEST ST @ LEROY S     335
EB HORACE HARDING EX     273
EB QUEENS BLVD @ 82N     245
WB ATLANTIC AVE @ CL     229
Name: count, dtype: int64

Set the index to `Vehicle Color`.

In [15]:
df = df.reset_index().set_index('Vehicle Color')

Determine the most common make of vehicles that were either red or blue

In [16]:
(df.loc[['BLUE', 'RED'], 'Vehicle Make'].value_counts().head(1))

Vehicle Make
HONDA    39353
Name: count, dtype: int64

What three car makes were most often ticketed from January 2 through January 10?

In [17]:
df = df.reset_index()   # undo the setting of the index from the previous cell

# let's do it in chained format:

(
    df
    .set_index('Issue Date')
    .sort_index()
    .loc['01/02/2020 12:00:00 AM':'01/10/2020 23:59:59 PM',
         'Vehicle Make']
    .value_counts()
    .head(3)
)

Vehicle Make
FORD     38958
TOYOT    37096
HONDA    35962
Name: count, dtype: int64

How many tickets did the second-most-ticketed car get in 2020?

In [18]:
df = df.reset_index()
df['Plate ID'].value_counts().head(2)

Plate ID
BLANKPLATE    8882
2704819       1535
Name: count, dtype: int64

What state was that car from?

In [19]:
df = df.set_index('Plate ID')
df.loc['2704819', 'Registration State']

Plate ID
2704819    IN
2704819    IN
2704819    IN
2704819    IN
2704819    IN
           ..
2704819    IN
2704819    IN
2704819    IN
2704819    IN
2704819    IN
Name: Registration State, Length: 1535, dtype: object

Was it always ticketed in the same location?

In [20]:
df.loc['2704819', 'Street Name'].value_counts()

Street Name
8th Ave                 395
Penn Plz                230
7th Ave                  92
9th Ave                  63
Broadway                 57
                       ...
WEST 36 STREET            1
N/S W 25 ST               1
AVENUE OF THE AMERIC      1
WEST 41 ST                1
N/S W 31 ST               1
Name: count, Length: 113, dtype: int64

# 22

Read in the scores file, only keeping the `Year`, `State.Code`, `Total.Math`, `Total.Test-takers`, and `Total.Verbal` columns.

In [22]:
sat_scores = pd.read_csv('./data/sat-scores.csv',
                         usecols= ['Year', 'State.Code', 'Total.Math', 'Total.Test-takers', 'Total.Verbal'])

Create a multi-index based on the year and the two-letter state code.

In [29]:
df = sat_scores.set_index(['Year', 'State.Code'])

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 577 entries, (np.int64(2005), 'AL') to (np.int64(2015), 'WY')
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Total.Math         577 non-null    int64
 1   Total.Test-takers  577 non-null    int64
 2   Total.Verbal       577 non-null    int64
dtypes: int64(3)
memory usage: 17.6+ KB

Determine how many people took the SAT in 2005.

In [35]:
df.loc[2005, 'Total.Test-takers'].sum()

np.int64(1344824)

Determine the average SAT math score in 2010 from New York (NY), New Jersey (NJ), Massachusetts (MA), and Illinois (IL).

In [36]:
df.loc[(2010, ['NY', 'NJ', 'MA', 'IL']), 'Total.Math'].mean()

np.float64(535.25)

Determine the average SAT verbal score in 2012–2015 from Arizona (AZ), California (CA), and Texas (TX).

In [37]:
df.loc[([2012,2013,2014,2015], ['AZ', 'CA', 'TX']), 'Total.Verbal'].mean()

np.float64(497.3333333333333)

# 23

Read the data file (`olympic_athlete_events.csv`) into a data frame, keep these columns: `Age`, `Height`, `Team`, `Year`, `Season`, `City`, `Sport`,
`Event`, and `Medal`.

The multi-index should be based on `Year`, `Season`, `Sport`, and `Event`.

In [42]:
olympic_athlete_events = pd.read_csv('./data/olympic_athlete_events.csv',
                                     usecols=['Age', 'Height', 'Team', 'Year', 'Season', 'City', 'Sport', 'Event', 'Medal'],
                                     index_col= ['Year', 'Season', 'Sport', 'Event'])

In [43]:
olympic_athlete_events.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 271116 entries, (np.int64(1992), 'Summer', 'Basketball', "Basketball Men's Basketball") to (np.int64(2002), 'Winter', 'Bobsleigh', "Bobsleigh Men's Four")
Data columns (total 5 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Age     261642 non-null  float64
 1   Height  210945 non-null  float64
 2   Team    271116 non-null  object
 3   City    271116 non-null  object
 4   Medal   39783 non-null   object
dtypes: float64(2), object(3)
memory usage: 11.7+ MB

In [46]:
df = olympic_athlete_events.sort_index()
df.head()

                                                     Age  Height  \
Year Season Sport     Event
1896 Summer Athletics Athletics Men's 1,500 metres  24.0     NaN
                      Athletics Men's 1,500 metres   NaN     NaN
                      Athletics Men's 1,500 metres  22.0     NaN
                      Athletics Men's 1,500 metres  23.0   154.0
                      Athletics Men's 1,500 metres  21.0     NaN

                                                             Team    City  \
Year Season Sport     Event
1896 Summer Athletics Athletics Men's 1,500 metres  United States  Athina
                      Athletics Men's 1,500 metres         Greece  Athina
                      Athletics Men's 1,500 metres      Australia  Athina
                      Athletics Men's 1,500 metres        Germany  Athina
                      Athletics Men's 1,500 metres         Greece  Athina

                                                     Medal
Year Season Sport     Event
1896 Summer Athletics Athletics Men's 1,500 metres  Silver
                      Athletics Men's 1,500 metres     NaN
                      Athletics Men's 1,500 metres    Gold
                      Athletics Men's 1,500 metres     NaN
                      Athletics Men's 1,500 metres     NaN

What is the average age of the competing athletes in summer games held between 1936 and 2000?

In [47]:
df.loc[(slice(1936,2000), 'Summer'), 'Age'].mean()

np.float64(25.026883940421765)

Which team won the most medals in all archery events?

In [51]:
df.dropna(subset='Medal').loc[(slice(None), 'Summer', 'Archery'), 'Team'].value_counts()

Team
South Korea           69
Belgium               52
France                48
United States         41
China                 19
Italy                 15
Great Britain         13
Chinese Taipei         9
Netherlands            9
Ukraine                8
Cincinnati Archers     8
Japan                  7
Germany                7
Soviet Union           7
Finland                6
Australia              5
Boston Archers         4
Unified Team           4
Potomac Archers        4
Russia                 4
Poland                 4
Spain                  3
Indonesia              3
Sweden                 2
Mexico                 2
Name: count, dtype: int64

Starting in 1980, what is the average height of the “Table Tennis Women’s Team” event?

In [52]:
df.loc[(slice(1980, None), 'Summer', slice(None), 'Table Tennis Women\'s Team'), 'Height'].mean()

np.float64(165.04827586206898)

Starting in 1980, what is the average height of both “Table Tennis Women’s Team” and “Table Tennis Men’s Team”?

In [53]:
df.loc[(slice(1980, None), 'Summer', slice(None), ['Table Tennis Men\'s Team', 'Table Tennis Women\'s Team']), 'Height'].mean()

np.float64(171.26643598615917)

Using `xs`, we can shorten that query to:

In [73]:
df.xs('Table Tennis Women\'s Team', level='Event')['Height'].mean()
# if we didn't know the season, we could use:
# df.xs(('Summer', 'Table Tennis Women\'s Team'), level=['Season', 'Event'])['Height'].mean()

np.float64(165.04827586206898)

A more general way to retrieve from a multi-index is `IndexSlice`.

In [59]:
from pandas import IndexSlice as idx

In [60]:
df.loc[idx[1980:2016, :, 'Swimming':'Table tennis'], :]

                                                                 Age  Height  \
Year Season Sport        Event
1980 Summer Swimming     Swimming Men's 1,500 metres Freestyle  19.0   185.0
                         Swimming Men's 1,500 metres Freestyle  18.0   181.0
                         Swimming Men's 1,500 metres Freestyle  19.0   178.0
                         Swimming Men's 1,500 metres Freestyle  21.0   184.0
                         Swimming Men's 1,500 metres Freestyle  16.0   174.0
...                                                              ...     ...
2016 Summer Table Tennis Table Tennis Women's Team              26.0   166.0
                         Table Tennis Women's Team              20.0   166.0
                         Table Tennis Women's Team              25.0   162.0
                         Table Tennis Women's Team              28.0   165.0
                         Table Tennis Women's Team              22.0   168.0

                                                                         Team  \
Year Season Sport        Event
1980 Summer Swimming     Swimming Men's 1,500 metres Freestyle  Great Britain
                         Swimming Men's 1,500 metres Freestyle   Soviet Union
                         Swimming Men's 1,500 metres Freestyle          Spain
                         Swimming Men's 1,500 metres Freestyle  Great Britain
                         Swimming Men's 1,500 metres Freestyle         Brazil
...                                                                       ...
2016 Summer Table Tennis Table Tennis Women's Team                  Singapore
                         Table Tennis Women's Team              United States
                         Table Tennis Women's Team                  Australia
                         Table Tennis Women's Team              United States
                         Table Tennis Women's Team                  Singapore

                                                                          City  \
Year Season Sport        Event
1980 Summer Swimming     Swimming Men's 1,500 metres Freestyle          Moskva
                         Swimming Men's 1,500 metres Freestyle          Moskva
                         Swimming Men's 1,500 metres Freestyle          Moskva
                         Swimming Men's 1,500 metres Freestyle          Moskva
                         Swimming Men's 1,500 metres Freestyle          Moskva
...                                                                        ...
2016 Summer Table Tennis Table Tennis Women's Team              Rio de Janeiro
                         Table Tennis Women's Team              Rio de Janeiro
                         Table Tennis Women's Team              Rio de Janeiro
                         Table Tennis Women's Team              Rio de Janeiro
                         Table Tennis Women's Team              Rio de Janeiro

                                                                 Medal
Year Season Sport        Event
1980 Summer Swimming     Swimming Men's 1,500 metres Freestyle     NaN
                         Swimming Men's 1,500 metres Freestyle  Silver
                         Swimming Men's 1,500 metres Freestyle     NaN
                         Swimming Men's 1,500 metres Freestyle     NaN
                         Swimming Men's 1,500 metres Freestyle     NaN
...                                                                ...
2016 Summer Table Tennis Table Tennis Women's Team                 NaN
                         Table Tennis Women's Team                 NaN
                         Table Tennis Women's Team                 NaN
                         Table Tennis Women's Team                 NaN
                         Table Tennis Women's Team                 NaN

[17935 rows x 5 columns]

How tall was the tallest-ever tennis player in Olympic games from 1980 until 2016?

Since Tennis is a summer sport, let's remove `Season` from the index.

In [68]:
df = df.reset_index('Season')

In [69]:
df.loc[(slice(1980,2020), 'Tennis'), 'Height'].max()

np.float64(208.0)

In which city were the most gold medals awarded from 1980 onward?

In [71]:
df.loc[1980:].loc[lambda df_: df_['Medal'] == 'Gold', 'City'].value_counts()

City
Beijing           671
Rio de Janeiro    665
Athina            664
Sydney            663
London            632
Atlanta           608
Barcelona         559
Seoul             520
Los Angeles       497
Moskva            457
Sochi             202
Torino            176
Vancouver         174
Salt Lake City    162
Nagano            145
Lillehammer       110
Albertville       104
Calgary            87
Sarajevo           74
Lake Placid        72
Name: count, dtype: int64

How many gold medals were received by the United States since 1980?

In [72]:
df.loc[1980:].loc[lambda df_: (df_['Team'] == 'United States') & (df_['Medal'] == 'Gold'), 'City'].count()

np.int64(1257)

# 24

In [77]:
df = olympic_athlete_events.reset_index()[['Age', 'Height', 'Team', 'Year', 'Season', 'Sport', 'Medal']]
df = df.loc[df['Team'].isin(['Great Britain', 'France', 'United States', 'Switzerland', 'China', 'India'])]
df = df.loc[df['Year'] >= 1980]

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27893 entries, 0 to 271037
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     27879 non-null  float64
 1   Height  27350 non-null  float64
 2   Team    27893 non-null  object
 3   Year    27893 non-null  int64
 4   Season  27893 non-null  object
 5   Sport   27893 non-null  object
 6   Medal   5256 non-null   object
dtypes: float64(2), int64(1), object(4)
memory usage: 1.7+ MB